// automatically generated by arduino-cmake
#line 1 "/home/blaster/Megamind/Megamind.ino"
/**
 *  Megamind Arduino firmware
 *
 *  22/09/2017
 *  Tales Luna <tales.ferreira.luna@gmail.com>
 *
 */

#include <Arduino.h>
#include <MegamindSensors.h>
#include <MegamindCommands.h>

#line 15 "/home/blaster/Megamind/Megamind_Megamind.ino.cpp"
#include "Arduino.h"

//=== START Forward: /home/blaster/Megamind/Megamind.ino
 void setup() ;
 void setup() ;
 void loop() ;
 void loop() ;
//=== END Forward: /home/blaster/Megamind/Megamind.ino
#line 11 "/home/blaster/Megamind/Megamind.ino"


void setup() {
    Serial.begin(9600);
    setupSensors();
}

void loop() {
    // Aways read serial inputs
    loopCommands();
}